#
# (C) Copyright 2018
# NVIDIA Corporation <www.nvidia.com>
#
# SPDX-License-Identifier:     GPL-2.0
#

# Make this first.
# It doesn't really matter, but makes the binary layout a bit more obvious.
obj-y += mon_vecs.o

obj-y += mon_dbg.o
obj-y += mon_entry.o
obj-y += mon_lib.o
obj-y += mon_smc.o
