#
# (C) Copyright 2010,2011 Nvidia Corporation.
#
# (C) Copyright 2000-2008
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += ap.o
obj-y += board.o
obj-y += cache.o
obj-y += clock.o
obj-$(CONFIG_TEGRA_LP0) += crypto.o
obj-y += lowlevel_init.o
obj-y += pinmux-common.o
obj-$(CONFIG_DISPLAY_CPUINFO) += sys_info.o
obj-$(CONFIG_TEGRA124_LP0) += t1x4_warmboot.o
obj-y += vpr.o
