#
# (C) Copyright 2013-2021
# NVIDIA Corporation <www.nvidia.com>
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y	+= clock.o
obj-y	+= funcmux.o
obj-y	+= rp4_support.o
obj-y	+= xusb-padctl.o
obj-y	+= ../xusb-padctl-common.o
