# Copyright (c) 2013-2017, NVIDIA CORPORATION.
#
# SPDX-License-Identifier: GPL-2.0
#

obj-y	+= clock.o
obj-y	+= funcmux.o
obj-y  += ../nvtboot_ll.o
obj-y  += ../nvtboot_mem.o
obj-y  += ../nvtboot_board.o
obj-y	+= pinmux.o
obj-y	+= xusb-padctl.o
obj-y	+= ../ft_board_info.o
obj-y	+= ../xusb-padctl-common.o
